"""Put a place's characters into its OpenUSD stage: who is there, how many, where and doing what, from the place's
cast (`data/characters/<place>.json`), each one a skinned character (tools/characters/skel_usd.py) with its clip.

    .venv/bin/python tools/characters/cast.py <place> --stage <the place's stage folder> [--bodies <built bodies>]

It writes `<stage>/layers/characters.usda`, a layer of its own that the stage's root holds between the creator's edit
layer and the framework's base (tools/usd/export.py), and each character's asset once into
`<stage>/assets/characters/`. The bodies are the people tools' built files (`$MOTION_WORK/bodies`, by default
~/.farm-factory-motion/work/bodies; tools/characters/people/run.sh builds them).

A cast has three kinds of entry, and nothing is placed that is not one of them:

- `people`: one named character each, at a spot (`at`, metres in the place's own frame), turned to face a point
  (`facing_to`), doing one clip (`doing`), optionally walking a `path` of points at `pace` metres a second, or
  `held` still at the clip's start (a body that does not breathe: the game pauses its clip there).
- `groups`: a few to a few dozen characters mixed from the kit (a build, a face, a hairstyle and an outfit from one
  seed each), spread along a `band` from a seed, each playing one of the group's clips, out of step by `phase_step`.
- `crowd`: many copies of one cheap body (the kit's `far` body, 1,220 triangles) as one UsdGeom.PointInstancer: a
  few dozen prototypes (each clip at a few phases, in each palette of clothes) dealt over spots spread from a seed,
  standing on the cast's raised `tiers`, turned to face a point with a little turn and height jitter.

Every entry says `why` it is there: a character needs a reason to be in a place (the game 2099's rule, ADR-0007).
The kit mix and the spreads repeat the game's rules with this module's own seeded generator, so the same cast
always gives the same people in the same spots; they are not the game's individual draws (Godot's generator is not
repeated here).

Each character is a prim `/<place>/Characters/<name>` referencing its asset, with its transform (translate, turn
about up, scale), the clip it plays (the Skeleton's `skel:animationSource`), where in the clip it starts (the
reference's time offset) and the body parts it wears (the rest made invisible). The layer runs at 30 time codes a
second, as the clips do.
"""
import argparse
import json
import math
import os
import pathlib
import random
import sys

from pxr import Gf, Sdf, Usd, UsdGeom, UsdShade, UsdSkel, Vt

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(HERE))
import skel_usd  # noqa: E402

CASTS = REPO / "data/characters"
BODIES = pathlib.Path(os.environ.get("MOTION_WORK", pathlib.Path.home() / ".farm-factory-motion/work")) / "bodies"
LAYER = "layers/characters.usda"
ASSETS = "assets/characters"
NOTE = "Generated by tools/characters/cast.py from the place's cast (data/characters); rewritten on every run."

# The crew kit (the people tools' kit.py): a mix is a build, a face of the same sex, a hairstyle, a work suit colour
# and a plain outfit, all from one seed.
KIT_MEN = {"builds": ["m_slim", "m_avg", "m_broad"], "faces": ["f1", "f3", "f5"], "hair": ["buzz", "side", "bun"]}
KIT_WOMEN = {"builds": ["w_slim", "w_avg", "w_broad"], "faces": ["f2", "f4", "f6"],
             "hair": ["bob", "pixie", "bun", "side"]}
KIT_SCHEMES = ["navy", "olive", "maroon"]
KIT_PLAIN = ["jacket_blue", "coat_grey", "uniform_olive"]
# How far a crowd's spot is drawn again when it falls on somebody or on ground kept off, before it is kept anyway.
CLEAR_TRIES = 8
# A group member whose look an earlier character has is drawn again from its seed stepped on this far, at most this
# many times (the kit has 63 looks: 27 men's and 36 women's builds, faces and hair).
MIX_STEP = 1000
MIX_TRIES = 200
# A walk's pace in metres a second when the cast gives none: the walk clip's own (the game's crew walk).
WALK_PACE = 1.333


# --- who ----------------------------------------------------------------------------------------------------------

def kit_mix(seed):
    """One person from the kit by a seed: their build's file and the body parts they wear in each outfit."""
    draw = random.Random(seed)
    sex = KIT_WOMEN if draw.random() < 0.5 else KIT_MEN
    build = draw.choice(sex["builds"])
    face = draw.choice(sex["faces"])
    hair = draw.choice(sex["hair"])
    scheme = draw.choice(KIT_SCHEMES)
    plain = draw.choice(KIT_PLAIN)
    head = [f"head_{face}", f"hair_{hair}_{face}"]
    return {"character": f"kit_{build}",
            "worn": {"plain": [f"plain_{plain}"] + head, "work": [f"work_{scheme}"] + head, "suit": ["suit"]}}


def look_of(character, worn):
    """Who a character looks like: its body file and, for a kit mix, the face and hair it wears (a named body has its
    own). Two characters with the same look are the same person, whatever else they wear."""
    return (character, *sorted(part for part in (worn or []) if part.startswith(("head_", "hair_"))))


def unseen_mix(seed, outfit, taken):
    """A kit mix from a seed whose look nobody in `taken` has yet (the seed stepped on by MIX_STEP until one is new),
    added to `taken`: a place never shows the same person twice."""
    for tries in range(MIX_TRIES):
        mix = kit_mix(seed + tries * MIX_STEP)
        look = look_of(mix["character"], mix["worn"][outfit])
        if look not in taken:
            taken.add(look)
            return mix
    raise ValueError(f"no new person from the kit after {MIX_TRIES} draws from seed {seed}: the kit has too few looks")


def facing_degrees(at, to):
    """The turn about up that faces a character (whose front is -z) at a point, in degrees."""
    return math.degrees(math.atan2(at[0] - to[0], at[2] - to[2]))


# --- where --------------------------------------------------------------------------------------------------------

def band_places(group):
    """A group's spots: evenly along the band's length with a jitter, anywhere across it (the game's front row)."""
    draw = random.Random(group["seed"])
    left, near, across, along = group["band"]
    places = []
    for number in range(group["count"]):
        z = near + along * (number + draw.random()) / group["count"]
        places.append([draw.uniform(left, left + across), group.get("height", 0.0), z])
    return places


def raised_ground(crowd):
    """The cast's raised boxes (x, y, z, wide, high, long): each tier and the half step round it, as the game
    raises its square (EarthSite.square_ground)."""
    tread, half_step = crowd.get("tier_tread", 0.0), crowd.get("tier_half_step", 0.0)
    boxes = []
    for x, y, z, wide, high, long in crowd.get("tiers", []):
        boxes.append((x, 0.0, z - tread, wide + tread, y + high - half_step, long + 2 * tread))
        boxes.append((x, y, z, wide, high, long))
    return boxes


def ground_at(boxes, x, z):
    """How high the ground stands at a spot: the top of the highest raised box over it, or 0."""
    tops = [box[1] + box[4] for box in boxes if box[0] <= x <= box[0] + box[3] and box[2] <= z <= box[2] + box[5]]
    return max(tops, default=0.0)


def tier_steps(crowd):
    """The half steps round the tiers, which nobody stands on: (x, z, wide, long) strips on three sides."""
    tread = crowd.get("tier_tread", 0.0)
    steps = []
    for x, _, z, wide, _, long in crowd.get("tiers", []):
        steps.append((x + wide, z - tread, tread, long + 2 * tread))
        steps.append((x, z - tread, wide, tread))
        steps.append((x, z + long, wide, tread))
    return steps


def inside(rectangle, x, z):
    left, near, wide, long = rectangle
    return left <= x <= left + wide and near <= z <= near + long


def crowd_spot(draw, crowd, kept_off, keep_clear):
    """A random spot on the spread, drawn again while it is on ground kept off or too near somebody kept clear of."""
    left, near, wide, long = crowd["spread"]
    radius = crowd.get("clear_radius", 0.0)
    for _ in range(CLEAR_TRIES):
        x, z = draw.uniform(left, left + wide), draw.uniform(near, near + long)
        clear = all(math.hypot(x - other[0], z - other[2]) >= radius for other in keep_clear)
        if clear and not any(inside(rectangle, x, z) for rectangle in kept_off):
            break
    return x, z


def crowd_copies(crowd, keep_clear):
    """Every copy of the crowd: spot on its ground, turn (degrees), height share, clip, phase and palette."""
    draw = random.Random(crowd["seed"])
    kept_off = [tuple(rectangle) for rectangle in crowd.get("kept_off", [])] + tier_steps(crowd)
    boxes = raised_ground(crowd)
    to = crowd["facing_to"]
    copies = []
    for _ in range(crowd["count"]):
        x, z = crowd_spot(draw, crowd, kept_off, keep_clear)
        at = [x, ground_at(boxes, x, z), z]
        turn = facing_degrees(at, to) + math.degrees(draw.uniform(-crowd["turn_jitter"], crowd["turn_jitter"]))
        tall = 1.0 + draw.uniform(-crowd["height_jitter"], crowd["height_jitter"])
        clip = draw.choices(range(len(crowd["doing"])), weights=crowd["shares"])[0]
        phase = draw.randrange(crowd["phases"])
        palette = draw.choices(range(len(crowd["palettes"])), weights=crowd["palette_shares"])[0]
        copies.append({"at": at, "turn": turn, "tall": tall, "clip": clip, "phase": phase, "palette": palette})
    return copies


def characters_of(cast):
    """Every single character of the cast (its people and its groups' members), each with its spot, turn, clip,
    start (a share of its clip) and the body parts it wears; the crowd is not among them."""
    found = []
    for person in cast.get("people", []):
        found.append({"name": person["name"], "character": person["character"], "at": person["at"],
                      "turn": facing_degrees(person["at"], person["facing_to"]), "doing": person["doing"],
                      "start": person.get("start", 0.0), "worn": person.get("worn"), "path": person.get("path"),
                      "pace": person.get("pace", WALK_PACE), "held": person.get("held", False)})
    taken = {look_of(person["character"], person.get("worn")) for person in found}
    for group in cast.get("groups", []):
        outfit = group.get("outfit", "plain")
        for number, at in enumerate(band_places(group)):
            mix = unseen_mix(group["seed"] + number, outfit, taken)
            found.append({"name": f"{group['name']}_{number}", "character": mix["character"], "at": at,
                          "turn": facing_degrees(at, group["facing_to"]),
                          "doing": group["doing"][number % len(group["doing"])],
                          "start": (number * group.get("phase_step", 0.0)) % 1.0,
                          "worn": mix["worn"][outfit], "path": None, "pace": WALK_PACE,
                          "held": False})
    return found


# --- writing ------------------------------------------------------------------------------------------------------

def asset_of(character, bodies, out):
    """The character's asset in the stage, converted from its built body when that is newer."""
    body = pathlib.Path(bodies) / f"{character}.glb"
    if not body.exists():
        raise FileNotFoundError(f"no built body for {character} at {body}; build it with tools/characters/people/run.sh")
    target = out / ASSETS / f"{character}.usdc"
    if not target.exists() or target.stat().st_mtime < body.stat().st_mtime:
        skel_usd.convert(body, out / ASSETS)
    return target


def asset_facts(path):
    """The asset's body parts (mesh nodes) and its clips' lengths in seconds."""
    asset = Usd.Stage.Open(str(path))
    body = asset.GetPrimAtPath("/Character/Turned/Body")
    root = asset.GetPrimAtPath("/Character")
    return [child.GetName() for child in body.GetChildren()], dict(root.GetCustomDataByKey("score:clip_seconds"))


def referenced(stage, path, asset, start_seconds):
    """A prim referencing the character's asset, its clip started `start_seconds` in."""
    prim = stage.DefinePrim(path, "SkelRoot")
    offset = Sdf.LayerOffset(-start_seconds * skel_usd.RATE)
    prim.GetReferences().AddReference(Sdf.Reference(f"../{ASSETS}/{asset.name}", layerOffset=offset))
    return prim


def dressed(stage, path, parts, worn):
    """Every body part shown that the character wears, every other made invisible."""
    for part in parts:
        holder = UsdGeom.Imageable(stage.OverridePrim(f"{path}/Turned/Body/{part}"))
        holder.CreateVisibilityAttr().Set(UsdGeom.Tokens.inherited if part in worn else UsdGeom.Tokens.invisible)


def playing(stage, path, clip, clips):
    """The character's Skeleton set to play one of its clips."""
    if clip not in clips:
        raise ValueError(f"{path}: no clip {clip!r} in its body (has {sorted(clips)})")
    skeleton = stage.OverridePrim(f"{path}/Turned/Skeleton")
    skeleton.CreateRelationship("skel:animationSource").SetTargets([Sdf.Path(f"{path}/Animations/{clip}")])


def held_still(stage, path, asset, clip, start_seconds):
    """The character's Skeleton set to a pose of its own: its clip's joints at `start_seconds` in, with no time
    samples, so it does not move (a SkelAnimation written into the characters layer beside it)."""
    body = Usd.Stage.Open(str(asset))
    source = UsdSkel.Animation(body.GetPrimAtPath(f"/Character/Animations/{clip}"))
    time = start_seconds * skel_usd.RATE
    pose = UsdSkel.Animation.Define(stage, f"{path}/Held")
    pose.CreateJointsAttr(source.GetJointsAttr().Get())
    pose.CreateRotationsAttr(source.GetRotationsAttr().Get(time))
    pose.CreateTranslationsAttr(source.GetTranslationsAttr().Get(time))
    pose.CreateScalesAttr(source.GetScalesAttr().Get(time))
    skeleton = stage.OverridePrim(f"{path}/Turned/Skeleton")
    skeleton.CreateRelationship("skel:animationSource").SetTargets([pose.GetPath()])


def placed(prim, at, turn):
    """The character's transform: its spot and its turn about up."""
    xform = UsdGeom.Xformable(prim)
    xform.ClearXformOpOrder()
    xform.AddTranslateOp().Set(Gf.Vec3d(*at))
    xform.AddRotateYOp().Set(float(turn))


def walked(prim, path, pace):
    """A walker's transform over time: along its path's points at its pace, turned along each leg."""
    xform = UsdGeom.Xformable(prim)
    xform.ClearXformOpOrder()
    move, turn = xform.AddTranslateOp(), xform.AddRotateYOp()
    seconds = 0.0
    for here, there in zip(path, path[1:]):
        heading = facing_degrees(here, there)
        move.Set(Gf.Vec3d(*here), seconds * skel_usd.RATE)
        turn.Set(heading, seconds * skel_usd.RATE)
        seconds += math.dist(here, there) / pace
        move.Set(Gf.Vec3d(*there), seconds * skel_usd.RATE)
        turn.Set(heading, seconds * skel_usd.RATE)


def palette_looks(stage, root, crowd):
    """One flat material per palette and part (skin, clothes, boots), from the cast's colours (0 to 255, sRGB)."""
    looks = {}
    for number, colours in enumerate(crowd["palettes"]):
        for part, colour in zip(crowd["palette_parts"], colours):
            look = UsdShade.Material.Define(stage, f"{root}/Looks/palette_{number}_{part}")
            shader = UsdShade.Shader.Define(stage, f"{root}/Looks/palette_{number}_{part}/surface")
            shader.CreateIdAttr("UsdPreviewSurface")
            linear = [((value / 255.0 + 0.055) / 1.055) ** 2.4 if value > 10 else value / 255.0 / 12.92
                      for value in colour]
            shader.CreateInput("diffuseColor", Sdf.ValueTypeNames.Color3f).Set(Gf.Vec3f(*linear))
            shader.CreateInput("roughness", Sdf.ValueTypeNames.Float).Set(1.0)
            look.CreateSurfaceOutput().ConnectToSource(shader.ConnectableAPI(), "surface")
            looks[number, part] = look
    return looks


def write_crowd(stage, root, crowd, keep_clear, asset):
    """The crowd as one PointInstancer: a prototype per clip, phase and palette, a copy per spot."""
    parts, clips = asset_facts(asset)
    looks = palette_looks(stage, root, crowd)
    instancer = UsdGeom.PointInstancer.Define(stage, root)
    UsdGeom.Scope.Define(stage, f"{root}/Prototypes")
    prototypes, index = [], {}
    for clip_number, clip in enumerate(crowd["doing"]):
        for phase in range(crowd["phases"]):
            for palette in range(len(crowd["palettes"])):
                path = f"{root}/Prototypes/{clip}_{phase}_{palette}"
                referenced(stage, path, asset, clips[clip] * phase / crowd["phases"])
                dressed(stage, path, parts, [crowd["body"]])
                playing(stage, path, clip, clips)
                for part_number, part in enumerate(crowd["palette_parts"]):
                    target = stage.OverridePrim(f"{path}/Turned/Body/{crowd['body']}/{part}_{part_number}")
                    UsdShade.MaterialBindingAPI.Apply(target).Bind(looks[palette, part])
                index[clip_number, phase, palette] = len(prototypes)
                prototypes.append(Sdf.Path(path))
    instancer.CreatePrototypesRel().SetTargets(prototypes)
    copies = crowd_copies(crowd, keep_clear)
    instancer.CreatePositionsAttr(Vt.Vec3fArray([Gf.Vec3f(*copy["at"]) for copy in copies]))
    instancer.CreateOrientationsAttr(Vt.QuathArray([
        Gf.Quath(Gf.Rotation(Gf.Vec3d(0, 1, 0), copy["turn"]).GetQuat()) for copy in copies]))
    instancer.CreateScalesAttr(Vt.Vec3fArray([Gf.Vec3f(copy["tall"]) for copy in copies]))
    instancer.CreateProtoIndicesAttr(Vt.IntArray([index[copy["clip"], copy["phase"], copy["palette"]]
                                                  for copy in copies]))
    return len(copies)


def held_by_root(place, out):
    """The stage's root made to hold the characters layer just over the base, if it does not yet (a stage exported
    before its cast was written; tools/usd/export.py keeps it there on every export after)."""
    root = Sdf.Layer.FindOrOpen(str(pathlib.Path(out) / f"{place}.usda"))
    if root is None:
        return
    paths = list(root.subLayerPaths)
    if f"./{LAYER}" in paths:
        return
    where = paths.index("./layers/base.usda") if "./layers/base.usda" in paths else len(paths)
    root.subLayerPaths.insert(where, f"./{LAYER}")
    root.Save()


def write_single(stage, root, single, bodies, out):
    """One character of the cast: its prim referencing its asset, placed or walking, dressed and playing its clip."""
    asset = asset_of(single["character"], bodies, out)
    parts, clips = asset_facts(asset)
    prim_path = f"{root}/{single['name']}"
    start = single["start"] * clips.get(single["doing"], 0.0)
    prim = referenced(stage, prim_path, asset, start)
    if single["path"]:
        walked(prim, single["path"], single["pace"])
    else:
        placed(prim, single["at"], single["turn"])
    dressed(stage, prim_path, parts, single["worn"] or skel_usd.DEFAULT_WORN)
    playing(stage, prim_path, single["doing"], clips)
    if single["held"]:
        held_still(stage, prim_path, asset, single["doing"], start)
    prim.SetCustomDataByKey("score:character", single["character"])


def write_layer(place, cast, out, bodies=BODIES):
    """The characters layer of the place's stage under `out`, rewritten whole; what it placed, by kind."""
    out = pathlib.Path(out)
    path = out / LAYER
    path.parent.mkdir(parents=True, exist_ok=True)
    layer = Sdf.Layer.FindOrOpen(str(path)) or Sdf.Layer.CreateNew(str(path))
    layer.Clear()
    layer.documentation = NOTE
    layer.timeCodesPerSecond = skel_usd.RATE
    layer.framesPerSecond = skel_usd.RATE
    stage = Usd.Stage.Open(layer)
    root = f"/{place}/Characters"
    UsdGeom.Scope.Define(stage, root)
    layer.GetPrimAtPath(f"/{place}").specifier = Sdf.SpecifierOver  # the place itself is the base's
    singles = characters_of(cast)
    for single in singles:
        write_single(stage, root, single, bodies, out)
    crowd_count = 0
    if cast.get("crowd"):
        crowd = cast["crowd"]
        keep_clear = [single["at"] for single in singles if single["name"].startswith(crowd.get("keep_clear_of", "-"))]
        crowd_count = write_crowd(stage, f"{root}/{crowd['name']}", crowd, keep_clear,
                                  asset_of(crowd["character"], bodies, out))
    layer.Save()
    held_by_root(place, out)
    return {"characters": len(singles), "crowd": crowd_count, "layer": str(path)}


def characters_drawn(cast):
    """Every body file the cast draws: its people's, its groups' kit builds and its crowd's."""
    drawn = [single["character"] for single in characters_of(cast)]
    if cast.get("crowd"):
        drawn.append(cast["crowd"]["character"])
    return drawn


def refuse_faulty(place, cast, stage_folder, bodies=BODIES):
    """Stop before writing a cast that shows somebody twice, walks somebody through a person or a thing on the
    place's stage (tools/characters/cast_check.py), or draws a body whose drapes are not commercial-OK
    (people/cloth_licence.py)."""
    import cast_check
    sys.path.insert(0, str(HERE / "people"))
    import cloth_licence
    faults = cast_check.check(cast, cast_check.stage_things(stage_folder / "layers/base.usda", place))
    faults += cloth_licence.body_faults(characters_drawn(cast), bodies)
    if faults:
        raise SystemExit(f"{place}'s cast is not written: " + "; ".join(faults))


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("place")
    parser.add_argument("--stage", required=True, type=pathlib.Path, help="the place's stage folder (export.py --out)")
    parser.add_argument("--bodies", type=pathlib.Path, default=BODIES)
    parser.add_argument("--cast", type=pathlib.Path, help="the cast file, by default data/characters/<place>.json")
    arguments = parser.parse_args()
    cast = json.loads((arguments.cast or CASTS / f"{arguments.place}.json").read_text())
    refuse_faulty(arguments.place, cast, arguments.stage, arguments.bodies)
    print(json.dumps(write_layer(arguments.place, cast, arguments.stage, arguments.bodies)))


if __name__ == "__main__":
    main()
