"""Write one place as an OpenUSD stage: the framework's canonical scene, which Blender and other engines load.

    .venv/bin/python tools/usd/export.py <place> --models <folder of the place's made .gltf> --out <folder>
                                         [--parts <folder of labelled parts, <model>-r<N>/<variant>.ply>]

A place today is its made models (glTF) and its layout (`data/kit/<place>.json`), read by the game in Godot. The
stage holds the same place in three layers, from the strongest down:

    <out>/<place>.usda           the stage itself: no prims, only its two layers and the units (metres, y up)
    <out>/layers/edit.usda       the creator's changes; made empty once and never written here again
    <out>/layers/base.usda       what the framework made; rewritten whole on every export
    <out>/assets/<model>.usdc    each model once, referenced by every object that is laid with it
    <out>/assets/textures/       the models' baked maps, as PNG

Because the edit layer sits above the base and objects keep their names across exports (`<row>_<n>`, the n-th
object of an inventory row in the layout's order), regenerating the base keeps every edit: a moved object stays
moved, a part given another surface keeps it.

Each object carries its kind (`score:kind`), its inventory row and name, its transform in metres (translate, turn
about up by the facing, tilt, scale, as the game lays it), its collision (a convex hull round the model, a guide
mesh with UsdPhysics' collision API, as the game's prop scene has it; no rigid body, so it is static), and its
sound (`score:sound`, the impact sound of its largest surface). Each part of a model is a GeomSubset named after
the library surface it is painted with, bound to a material of that name drawn with the model's baked maps, and
carrying that surface's sounds. A part can be given any of the place's library surfaces (`/<place>/Library`).
Mass and friction are not written: the game lays these pieces as static bodies with its default physics material
and the framework records neither yet.

Geometry is converted rather than referenced as glTF: usd-core and Blender's USD importer have no glTF file
format plugin, and a plain UsdGeomMesh with UsdPreviewSurface materials and PNG maps is what every USD reader
(Blender, Omniverse, Unreal, Houdini, usdview) loads. Library: usd-core (Pixar's OpenUSD, Tomorrow Open Source
Technology License 1.0: Apache 2.0 with a different trademark clause; commercial use allowed).
"""
import argparse
import json
import pathlib
import re
import sys

import numpy as np
import trimesh
from PIL import Image
from pxr import Gf, Kind, Sdf, Usd, UsdGeom, UsdLux, UsdPhysics, UsdShade, Vt
from scipy.spatial import cKDTree

REPO = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "tools/props"))
sys.path.insert(0, str(REPO / "tools/props/library"))
import glb_file  # noqa: E402
import library  # noqa: E402

KITS = REPO / "data/kit"
INVENTORIES = REPO / "data/inventory"
DETAILS = REPO / "data/library/details.json"
SOUNDS = REPO / "data/sound/surfaces.json"
# How many points of a labelled model the part lookup keeps at most: enough to tell parts apart a few
# millimetres wide, few enough that a million-face model never loads whole into the tree.
PART_POINTS = 400_000
EDIT_NOTE = ("The creator's changes to this place. The framework never writes this layer; it sits above the "
             "generated base, so every change here survives a regeneration.")
BASE_NOTE = "Generated by tools/usd/export.py from the place's layout and made models; rewritten on every export."


# --- reading the place --------------------------------------------------------------------------------------------

def read_gltf(path):
    """A .gltf with its .bin beside it, as glb_file's (document, list of each buffer view's bytes)."""
    document = json.loads(pathlib.Path(path).read_text())
    if len(document["buffers"]) != 1:
        raise ValueError(f"{path}: one buffer expected, found {len(document['buffers'])}")
    blob = (pathlib.Path(path).parent / document["buffers"][0]["uri"]).read_bytes()
    views = [blob[view.get("byteOffset", 0):view.get("byteOffset", 0) + view["byteLength"]]
             for view in document["bufferViews"]]
    return document, views


def model_geometry(path):
    """The model's one primitive: positions, normals, texture coordinates and triangles, in the file's metres."""
    document, views = read_gltf(path)
    primitives = [primitive for mesh in document["meshes"] for primitive in mesh["primitives"]]
    if len(primitives) != 1 or len(document["nodes"]) != 1 or set(document["nodes"][0]) - {"mesh", "name"}:
        raise ValueError(f"{path}: a made model is one untransformed node with one primitive")
    attributes = primitives[0]["attributes"]
    return {
        "positions": glb_file.accessor_array(document, views, attributes["POSITION"]).astype(np.float64),
        "normals": glb_file.accessor_array(document, views, attributes["NORMAL"]).astype(np.float64),
        "uvs": glb_file.accessor_array(document, views, attributes["TEXCOORD_0"]).astype(np.float64),
        "triangles": glb_file.accessor_array(document, views, primitives[0]["indices"]).reshape(-1, 3).astype(np.int64),
    }


def model_maps(path):
    """The model's baked maps by role (base_color, metal_roughness, normal), each the picture file it names."""
    document = json.loads(pathlib.Path(path).read_text())
    material = document["materials"][document["meshes"][0]["primitives"][0]["material"]]
    texture_of = {
        "base_color": material["pbrMetallicRoughness"].get("baseColorTexture"),
        "metal_roughness": material["pbrMetallicRoughness"].get("metallicRoughnessTexture"),
        "normal": material.get("normalTexture"),
    }
    found = {}
    for role, reference in texture_of.items():
        if reference is None:
            continue
        texture = document["textures"][reference["index"]]
        source = texture.get("extensions", {}).get("EXT_texture_webp", {}).get("source", texture.get("source"))
        found[role] = pathlib.Path(path).parent / document["images"][source]["uri"]
    return found


def labelled_take(parts, model):
    """The newest labelled take of a model (`<model>-r<N>`, highest N) in the parts folder, or None."""
    if parts is None:
        return None
    takes = [(int(match.group(1)), found) for found in pathlib.Path(parts).glob(f"{model}-r*")
             if (match := re.fullmatch(rf"{re.escape(model)}-r(\d+)", found.name)) and found.is_dir()]
    return max(takes)[1] if takes else None


def part_points(take, turn, size):
    """Each labelled part's points in the kit frame the made model stands in: turned by the kind's turn and fitted
    to its laid size on the middle of its foot, as the route's make_chunky does; (points, variant of each point)."""
    files = sorted(take.glob("*.ply"))
    if not files:
        raise ValueError(f"{take}: no labelled parts")
    meshes = [trimesh.load(found, process=False) for found in files]
    total = sum(len(mesh.vertices) for mesh in meshes)
    stride = max(1, total // PART_POINTS)
    points = np.vstack([np.asarray(mesh.vertices)[::stride] for mesh in meshes]) @ np.asarray(turn).reshape(3, 3).T
    names = np.concatenate([np.full(len(np.asarray(mesh.vertices)[::stride]), found.stem)
                            for mesh, found in zip(meshes, files)])
    low, high = points.min(axis=0), points.max(axis=0)
    foot = np.array([(low[0] + high[0]) / 2, low[1], (low[2] + high[2]) / 2])
    return (points - foot) * (np.asarray(size, dtype=np.float64) / (high - low)), names


def face_surfaces(geometry, points, names):
    """Each triangle's library surface: the part whose nearest labelled point lies under the triangle's middle."""
    middles = geometry["positions"][geometry["triangles"]].mean(axis=1)
    return names[cKDTree(points).query(middles)[1]]


def sound_of(variant, variants, sounds):
    """A library surface's sounds: the surface it sounds like (its own, else its family's) and that surface's
    footstep, impact, scrape and absorption."""
    surface = variants[variant].get("surface") or library.theme_library()["families"][variants[variant]["family"]]["surface"]
    entry = sounds["surfaces"].get(surface, sounds["fallback"])
    return dict(entry, surface=surface)


# --- the asset of one model ---------------------------------------------------------------------------------------

def png_maps(maps, textures):
    """Each baked map written as PNG into the textures folder; the asset-relative path of each by role."""
    textures.mkdir(parents=True, exist_ok=True)
    found = {}
    for role, source in maps.items():
        target = textures / f"{source.stem}.png"
        if not target.exists() or target.stat().st_mtime < source.stat().st_mtime:
            Image.open(source).save(target)
        found[role] = f"./textures/{target.name}"
    return found


def baked_material(stage, path, maps, surface):
    """A material drawn with the model's baked maps (UsdPreviewSurface), named for the library surface it paints;
    its surface's name, family and sounds ride on it."""
    material = UsdShade.Material.Define(stage, path)
    shader = UsdShade.Shader.Define(stage, f"{path}/surface")
    shader.CreateIdAttr("UsdPreviewSurface")
    reader = UsdShade.Shader.Define(stage, f"{path}/uv")
    reader.CreateIdAttr("UsdPrimvarReader_float2")
    reader.CreateInput("varname", Sdf.ValueTypeNames.String).Set("st")
    coordinates = reader.CreateOutput("result", Sdf.ValueTypeNames.Float2)
    for role, file in maps.items():
        texture = UsdShade.Shader.Define(stage, f"{path}/{role}")
        texture.CreateIdAttr("UsdUVTexture")
        texture.CreateInput("file", Sdf.ValueTypeNames.Asset).Set(file)
        texture.CreateInput("st", Sdf.ValueTypeNames.Float2).ConnectToSource(coordinates)
        texture.CreateInput("sourceColorSpace", Sdf.ValueTypeNames.Token).Set("sRGB" if role == "base_color" else "raw")
        if role == "base_color":
            shader.CreateInput("diffuseColor", Sdf.ValueTypeNames.Color3f).ConnectToSource(
                texture.CreateOutput("rgb", Sdf.ValueTypeNames.Float3))
        elif role == "metal_roughness":  # glTF packs roughness in green and metal in blue
            shader.CreateInput("roughness", Sdf.ValueTypeNames.Float).ConnectToSource(
                texture.CreateOutput("g", Sdf.ValueTypeNames.Float))
            shader.CreateInput("metallic", Sdf.ValueTypeNames.Float).ConnectToSource(
                texture.CreateOutput("b", Sdf.ValueTypeNames.Float))
        else:
            texture.CreateInput("scale", Sdf.ValueTypeNames.Float4).Set(Gf.Vec4f(2, 2, 2, 1))
            texture.CreateInput("bias", Sdf.ValueTypeNames.Float4).Set(Gf.Vec4f(-1, -1, -1, 0))
            shader.CreateInput("normal", Sdf.ValueTypeNames.Normal3f).ConnectToSource(
                texture.CreateOutput("rgb", Sdf.ValueTypeNames.Float3))
    material.CreateSurfaceOutput().ConnectToSource(shader.ConnectableAPI(), "surface")
    if surface is not None:
        material.GetPrim().CreateAttribute("score:surface", Sdf.ValueTypeNames.String).Set(surface)
    return material


def surface_attributes(prim, variant, variants, sounds):
    """The library surface a part is, with its family and its sounds, as score:* attributes on the part."""
    sound = sound_of(variant, variants, sounds)
    values = {"score:surface": variant, "score:family": variants[variant]["family"],
              "score:sound:surface": sound["surface"], "score:sound:footstep": sound["footstep"],
              "score:sound:impact": sound["impact"], "score:sound:scrape": sound["scrape"]}
    for name, value in values.items():
        prim.CreateAttribute(name, Sdf.ValueTypeNames.String).Set(value)
    if "absorbs" in sound:
        prim.CreateAttribute("score:sound:absorbs", Sdf.ValueTypeNames.Float).Set(float(sound["absorbs"]))


def render_mesh(stage, path, geometry):
    """The model's drawn mesh: its triangles, smooth normals and texture coordinates (flipped to USD's lower-left
    origin), never subdivided."""
    mesh = UsdGeom.Mesh.Define(stage, path)
    positions = geometry["positions"]
    mesh.CreatePointsAttr(Vt.Vec3fArray.FromNumpy(positions.astype(np.float32)))
    mesh.CreateFaceVertexCountsAttr(Vt.IntArray.FromNumpy(np.full(len(geometry["triangles"]), 3, dtype=np.int32)))
    mesh.CreateFaceVertexIndicesAttr(Vt.IntArray.FromNumpy(geometry["triangles"].reshape(-1).astype(np.int32)))
    mesh.CreateNormalsAttr(Vt.Vec3fArray.FromNumpy(geometry["normals"].astype(np.float32)))
    mesh.SetNormalsInterpolation(UsdGeom.Tokens.vertex)
    flipped = np.column_stack([geometry["uvs"][:, 0], 1.0 - geometry["uvs"][:, 1]]).astype(np.float32)
    UsdGeom.PrimvarsAPI(mesh).CreatePrimvar("st", Sdf.ValueTypeNames.TexCoord2fArray, UsdGeom.Tokens.vertex).Set(
        Vt.Vec2fArray.FromNumpy(flipped))
    mesh.CreateSubdivisionSchemeAttr(UsdGeom.Tokens.none)
    mesh.CreateDoubleSidedAttr(True)
    mesh.CreateExtentAttr([Gf.Vec3f(*positions.min(axis=0)), Gf.Vec3f(*positions.max(axis=0))])
    return mesh


def collision_mesh(stage, path, geometry):
    """The model's collision: a convex hull round it, as the game's prop scene has, a guide mesh (never drawn)
    with UsdPhysics' collision API and a convex hull approximation."""
    hull = trimesh.Trimesh(geometry["positions"], geometry["triangles"], process=False).convex_hull
    mesh = UsdGeom.Mesh.Define(stage, path)
    mesh.CreatePointsAttr(Vt.Vec3fArray.FromNumpy(np.asarray(hull.vertices, dtype=np.float32)))
    mesh.CreateFaceVertexCountsAttr(Vt.IntArray.FromNumpy(np.full(len(hull.faces), 3, dtype=np.int32)))
    mesh.CreateFaceVertexIndicesAttr(Vt.IntArray.FromNumpy(np.asarray(hull.faces, dtype=np.int32).reshape(-1)))
    mesh.CreateSubdivisionSchemeAttr(UsdGeom.Tokens.none)
    mesh.CreatePurposeAttr(UsdGeom.Tokens.guide)
    UsdPhysics.CollisionAPI.Apply(mesh.GetPrim())
    UsdPhysics.MeshCollisionAPI.Apply(mesh.GetPrim()).CreateApproximationAttr(UsdPhysics.Tokens.convexHull)
    return mesh


def part_subsets(stage, mesh, surfaces, maps, variants, sounds):
    """One GeomSubset per library surface over the faces painted with it, each bound to its own baked material;
    the name of the surface with the most area comes back (the model's sound)."""
    model_path = mesh.GetPath().GetParentPath()
    areas = trimesh.Trimesh(np.asarray(mesh.GetPointsAttr().Get()), np.asarray(
        mesh.GetFaceVertexIndicesAttr().Get()).reshape(-1, 3), process=False).area_faces
    for variant in sorted(set(surfaces)):
        faces = np.nonzero(surfaces == variant)[0].astype(np.int32)
        subset = UsdGeom.Subset.CreateGeomSubset(mesh, variant, UsdGeom.Tokens.face, Vt.IntArray.FromNumpy(faces),
                                                 UsdShade.Tokens.materialBind)
        material = baked_material(stage, model_path.AppendPath(f"Looks/{variant}"), maps, variant)
        UsdShade.MaterialBindingAPI.Apply(subset.GetPrim()).Bind(material)
        surface_attributes(subset.GetPrim(), variant, variants, sounds)
    UsdGeom.Subset.SetFamilyType(mesh, UsdShade.Tokens.materialBind, UsdGeom.Tokens.partition)
    return max(set(surfaces), key=lambda variant: areas[surfaces == variant].sum())


def write_asset(model, models, parts, turn, size, out, variants, sounds):
    """One model as its own USD file under <out>/assets: drawn mesh, parts, collision; its largest surface back
    (None when the model has no labelled parts)."""
    gltf = pathlib.Path(models) / f"{model}.gltf"
    geometry = model_geometry(gltf)
    maps = png_maps(model_maps(gltf), out / "assets/textures")
    stage = Usd.Stage.CreateNew(str(out / "assets" / f"{model}.usdc"))
    UsdGeom.SetStageUpAxis(stage, UsdGeom.Tokens.y)
    UsdGeom.SetStageMetersPerUnit(stage, 1.0)
    root = UsdGeom.Xform.Define(stage, f"/{model}")
    stage.SetDefaultPrim(root.GetPrim())
    Usd.ModelAPI(root).SetKind(Kind.Tokens.component)
    UsdGeom.Scope.Define(stage, f"/{model}/Looks")
    mesh = render_mesh(stage, f"/{model}/geo", geometry)
    collision_mesh(stage, f"/{model}/collision", geometry)
    take = labelled_take(parts, model)
    largest = None
    if take is None:
        UsdShade.MaterialBindingAPI.Apply(mesh.GetPrim()).Bind(baked_material(stage, f"/{model}/Looks/baked", maps, None))
    else:
        points, names = part_points(take, turn, size)
        largest = part_subsets(stage, mesh, face_surfaces(geometry, points, names), maps, variants, sounds)
    stage.GetRootLayer().Save()
    return largest


# --- the place's layers -------------------------------------------------------------------------------------------

def object_names(pieces):
    """Each piece's object name, `<row>_<n>`: the n-th piece of its inventory row in the layout's order, so a name
    means the same object in every export."""
    counts, names = {}, []
    for piece in pieces:
        counts[piece["row"]] = counts.get(piece["row"], 0) + 1
        names.append(f"{piece['row']}_{counts[piece['row']]}")
    return names


def library_materials(stage, place, root):
    """Every library surface the place takes, as a flat-coloured UsdPreviewSurface under <root>/Library (its
    palette colour, roughness and metal), for the creator to give a part; recipe and token ride along."""
    for name, spec in library.by_library(place).items():
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
            raise ValueError(f"library surface '{name}' is not a USD prim name")
        material = UsdShade.Material.Define(stage, f"{root}/Library/{name}")
        shader = UsdShade.Shader.Define(stage, f"{root}/Library/{name}/surface")
        shader.CreateIdAttr("UsdPreviewSurface")
        shader.CreateInput("diffuseColor", Sdf.ValueTypeNames.Color3f).Set(Gf.Vec3f(*spec["colour"]))
        shader.CreateInput("roughness", Sdf.ValueTypeNames.Float).Set(float(spec.get("roughness", 0.5)))
        shader.CreateInput("metallic", Sdf.ValueTypeNames.Float).Set(float(spec.get("metal", 0.0)))
        material.CreateSurfaceOutput().ConnectToSource(shader.ConnectableAPI(), "surface")
        for key in ("recipe", "token", "family"):
            material.GetPrim().CreateAttribute(f"score:{key}", Sdf.ValueTypeNames.String).Set(str(spec[key]))


def laid_object(stage, path, piece, row, asset, sound):
    """One object of the place: its model referenced, its transform as the game lays it, its kind, inventory row,
    name and sound."""
    xform = UsdGeom.Xform.Define(stage, path)
    xform.GetPrim().GetReferences().AddReference(asset)
    xform.AddTranslateOp().Set(Gf.Vec3d(*piece["at"]))
    xform.AddRotateYOp().Set(-float(piece.get("facing", 0.0)))
    xform.AddRotateXOp().Set(float(piece.get("tilt", 0.0)))
    xform.AddScaleOp().Set(Gf.Vec3f(float(piece.get("scale", 1.0))))
    values = {"score:kind": piece["kind"], "score:row": piece["row"], "score:model": piece["model"],
              "score:name": row.get("name", ""), "score:anchor": row.get("anchor", "")}
    if sound is not None:
        values.update({"score:sound": sound["impact"], "score:sound:surface": sound["surface"]})
    for name, value in values.items():
        xform.GetPrim().CreateAttribute(name, Sdf.ValueTypeNames.String).Set(value)
    xform.GetPrim().CreateAttribute("score:size", Sdf.ValueTypeNames.Float3).Set(Gf.Vec3f(*piece["size"]))


def lamp(stage, path, entry):
    """A lamp of the layout: a small sphere light where it hangs, its strength and reach as the game reads them."""
    light = UsdLux.SphereLight.Define(stage, path)
    light.AddTranslateOp().Set(Gf.Vec3d(*entry["at"]))
    light.CreateRadiusAttr(0.05)
    light.GetPrim().CreateAttribute("score:strength", Sdf.ValueTypeNames.Float).Set(float(entry.get("strength", 1.0)))
    light.GetPrim().CreateAttribute("score:range", Sdf.ValueTypeNames.Float).Set(float(entry.get("range", 6.0)))


def write_base(place, kit, inventory, assets, out):
    """The generated layer, rewritten whole: the place's root, its library surfaces, its objects and its lamps."""
    path = out / "layers/base.usda"
    path.parent.mkdir(parents=True, exist_ok=True)
    layer = Sdf.Layer.FindOrOpen(str(path)) or Sdf.Layer.CreateNew(str(path))
    layer.Clear()
    layer.documentation = BASE_NOTE
    stage = Usd.Stage.Open(layer)
    root = UsdGeom.Xform.Define(stage, f"/{place}")
    Usd.ModelAPI(root).SetKind(Kind.Tokens.assembly)
    Usd.ModelAPI(UsdGeom.Xform.Define(stage, f"/{place}/Objects")).SetKind(Kind.Tokens.group)
    UsdGeom.Scope.Define(stage, f"/{place}/Library")
    library_materials(stage, place, f"/{place}")
    rows = {row["id"]: row for row in inventory["rows"]}
    for name, piece in zip(object_names(kit["pieces"]), kit["pieces"]):
        model = piece["model"]
        laid_object(stage, f"/{place}/Objects/{name}", piece, rows.get(piece["row"], {}),
                    f"../assets/{model}.usdc", assets[model])
    if kit.get("lamps"):
        UsdGeom.Scope.Define(stage, f"/{place}/Lamps")
    for number, entry in enumerate(kit.get("lamps", []), start=1):
        lamp(stage, f"/{place}/Lamps/lamp_{number}", entry)
    layer.Save()


def ensure_edit(out):
    """The creator's layer: made empty the first time, left exactly as it is every time after."""
    path = out / "layers/edit.usda"
    if path.exists():
        return
    layer = Sdf.Layer.CreateNew(str(path))
    layer.documentation = EDIT_NOTE
    layer.Save()


def write_root(place, out):
    """The stage's own file: the edit layer over the base, metres, y up, the place as its default prim."""
    path = out / f"{place}.usda"
    layer = Sdf.Layer.FindOrOpen(str(path)) or Sdf.Layer.CreateNew(str(path))
    layer.Clear()
    layer.subLayerPaths.append("./layers/edit.usda")
    layer.subLayerPaths.append("./layers/base.usda")
    layer.defaultPrim = place
    layer.pseudoRoot.SetInfo("upAxis", UsdGeom.Tokens.y)
    layer.pseudoRoot.SetInfo("metersPerUnit", 1.0)
    layer.Save()
    return path


# --- the way in ---------------------------------------------------------------------------------------------------

def export(place, models, out, parts=None, kit_path=None, inventory_path=None):
    """Write the place's stage under `out` (base and assets rewritten, the edit layer kept) and return its path."""
    out = pathlib.Path(out)
    kit = json.loads(pathlib.Path(kit_path or KITS / f"{place}.json").read_text())
    inventory = json.loads(pathlib.Path(inventory_path or INVENTORIES / f"{place}.json").read_text())
    if kit.get("children"):
        raise NotImplementedError(f"{place}: child objects on a parent ({len(kit['children'])}) are not exported yet")
    details = json.loads(DETAILS.read_text())
    variants = library.variants(library.theme_library())
    sounds = json.loads(SOUNDS.read_text())
    (out / "assets").mkdir(parents=True, exist_ok=True)
    assets = {}
    for piece in kit["pieces"]:
        model = piece["model"]
        if model in assets:
            continue
        turn = details.get(piece["kind"], {}).get("turn", [1, 0, 0, 0, 1, 0, 0, 0, 1])
        largest = write_asset(model, models, parts, turn, piece["size"], out, variants, sounds)
        assets[model] = None if largest is None else sound_of(largest, variants, sounds)
    write_base(place, kit, inventory, assets, out)
    ensure_edit(out)
    return write_root(place, out)


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("place")
    parser.add_argument("--models", required=True, type=pathlib.Path)
    parser.add_argument("--out", required=True, type=pathlib.Path)
    parser.add_argument("--parts", type=pathlib.Path)
    arguments = parser.parse_args()
    print(export(arguments.place, arguments.models, arguments.out, arguments.parts))


if __name__ == "__main__":
    main()
