"""The far city as a place of its own: its towers, the land they stand on, the mountains behind and the harbour
water out to its shore, as one OpenUSD stage that the flat, the street, the square and the launch view each reference
where they stand (their scene record's `places` entry for `far_city`; tools/usd/scene.py write_places).

The owner on the demo (2026-10-09): a picture on the skyline is "cheating"; the far city is made by the framework, in
3D, from its own made towers. Its layout is far_city.py's plan (the same seed lays the same city: hundreds of towers
rows deep along a far shore, the business districts taller, code-built mountains behind); this module stands it up:

    /far_city/Towers      one point instancer: a prototype per tower kind (the kind's made model, converted once by
                          glb_asset.py, with its lit windows), an instance per tower of the plan, standing on the land
                          at its spot, turned to face the ring's middle as the plan turns it and scaled to the height
                          the plan deals it
    /far_city/Land        the waterfront's flat land, from the shore back to the mountains' foot
    /far_city/Mountains   the plan's mountain heights on its polar grid
    /far_city/Harbour     the water from the places' own harbour (radius HARBOUR_FROM) out to the shore, so no gap
                          of sky shows under the city; named Harbour, not Water, so a place that shows the city keeps it

    .venv/bin/python tools/usd/far_city_stage.py --seed 7 --out <stages folder> [--models <folder of made towers>]

writes <out>/far_city/far_city.usda, laid out as every place's stage (export.py: layers/base.usda rewritten whole,
layers/edit.usda the creator's, kept; assets/; inputs.json), beside the places that reference it as ../../far_city/.
Each kind's prototype names its launch inventory row (`score:row`), so a place showing the city shows those rows.
A tower kind's model is <models>/<row>.gltf, <row>_1.gltf or <row>.glb (far_city.MODELS by default). The city is laid
of the kinds that are made; a kind not made yet is left out and its lots dealt to the made ones (far_city.lay_towers),
never stood in for. The towers' made models carry no lit windows, so each kind's lit windows are laid here: small
quads of the library's lit-window surface on its upright faces, a share of them lit, floor by floor
(window_lights). Frame: EarthSite's metres, the water at height 0, bearings
clockwise from north (-z), as far_city.py.
"""
import argparse
import json
import math
import pathlib
import sys

import numpy as np
import trimesh
from pxr import Gf, Kind, Sdf, Usd, UsdGeom, Vt

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import complete  # noqa: E402
import export  # noqa: E402
import far_city  # noqa: E402
import glb_asset  # noqa: E402
import scene  # noqa: E402

PLACE = "far_city"
# The place whose library surfaces the city is painted from: the launch view, the harbour it stands across.
STYLE = "prologue_launch"
LAND_SURFACE = "concrete_dark"
MOUNTAIN_SURFACE = "foliage_leaf"
WATER_SURFACE = "harbour_water"
# The places' own harbour reaches 320 m (data/scene/launch.json `harbour`); the city's water starts a little inside it.
HARBOUR_FROM = 300.0
# The land's height over the water, and how far in front of the first row the waterfront starts.
LAND_HIGH = 2.0
LAND_FRONT = 20.0
WATER_HIGH = -0.02
# The lit windows: a storey's height, a bay's width along a face, a window's size (wide, tall), how far proud of the
# face it stands, the share of bays lit at night, which faces count as upright (the up part of their normal) and the
# surface they glow with. WINDOW and LIT are set by measurement, never by eye (tools/review/brightness.py, the towers'
# pixels in linear light against the game's shots from the launch's five cameras, 2026-10-10): at 1.4 x 1.2 m and 15%
# lit the towers showed 0.013 against the game's 0.048 to 0.140 (11% to 26% of it); the towers' light rises in step
# with window area times LIT (0.0007 + 0.42 of it), and at 2.2 x 1.8 m and 45% they show 0.079, the game's mean over
# the five (0.079); with the low block laid, the launch's five and the square's three balcony views read 0.58 to 1.53
# of their game shots, against 0.11 to 0.41 before. The flat's balcony camera frames the skyline lower than its game
# shot, so its pixels do not match and it is not counted.
FLOOR = 3.2
BAY = 3.0
WINDOW = (2.2, 1.8)
PROUD = 0.15
LIT = 0.45
UPRIGHT = 0.3
WINDOW_SURFACE = "window_lit"
BASE_NOTE = ("Generated by tools/usd/far_city_stage.py from far_city.py's seeded plan and the made tower kinds; "
             "rewritten on every run.")


def bearing_point(bearing, reach, height):
    """A point at a bearing (degrees clockwise from north, -z) and a reach from the ring's middle, at a height."""
    turn = math.radians(bearing)
    return (reach * math.sin(turn), height, -reach * math.cos(turn))


def polar_mesh(bearings, reaches, heights, surface):
    """A grid over bearings (columns) and reaches (rows, each row's reach per bearing) as a builders-style mesh."""
    points = np.array([bearing_point(bearing, reaches[row][column], heights[row][column])
                       for row in range(len(reaches)) for column, bearing in enumerate(bearings)], dtype=float)
    columns = len(bearings)
    triangles = []
    for row in range(len(reaches) - 1):
        for column in range(columns - 1):
            here = row * columns + column
            triangles += [[here, here + columns, here + 1], [here + 1, here + columns, here + columns + 1]]
    uvs = points[:, [0, 2]]
    return {"points": points, "triangles": np.array(triangles, dtype=np.int64), "uvs": uvs, "surface": surface}


def land_mesh(city):
    """The waterfront's land: from just in front of the shore back to where the mountains rise, flat at LAND_HIGH."""
    hills = city["mountains"]
    shore = hills["shore"]
    back = hills["reaches"][0]
    reaches = [[edge - LAND_FRONT for edge in shore], [edge + back for edge in shore]]
    heights = [[LAND_HIGH] * len(shore)] * 2
    return polar_mesh(hills["bearings"], reaches, heights, LAND_SURFACE)


def mountain_mesh(city):
    """The plan's mountains: its heights on its polar grid, each row's reach behind that bearing's shore."""
    hills = city["mountains"]
    reaches = [[edge + reach for edge in hills["shore"]] for reach in hills["reaches"]]
    heights = [[max(LAND_HIGH, height) for height in row] for row in hills["heights"]]
    return polar_mesh(hills["bearings"], reaches, heights, MOUNTAIN_SURFACE)


def harbour_mesh(city):
    """The water from HARBOUR_FROM out to under the land's front edge, over the city's bearings."""
    hills = city["mountains"]
    reaches = [[HARBOUR_FROM] * len(hills["shore"]), [edge - LAND_FRONT + 5.0 for edge in hills["shore"]]]
    heights = [[WATER_HIGH] * len(hills["shore"])] * 2
    return polar_mesh(hills["bearings"], reaches, heights, WATER_SURFACE)


def model_file(models, row):
    """A tower kind's made model in the models folder, or None while it is not made."""
    for name in (f"{row}.gltf", f"{row}_1.gltf", f"{row}.glb"):
        found = pathlib.Path(models) / name
        if found.exists():
            return found
    return None


def made_kinds(models):
    """The tower kinds that have a made model in the folder."""
    return {kind["row"] for kind in far_city.kinds() if model_file(models, kind["row"]) is not None}


def window_lights(model, seed):
    """A tower model's lit windows as one mesh in the model's own frame: a WINDOW sized quad, LIFT proud of the face,
    on a share LIT of the bays of its upright faces (faces within UPRIGHT of vertical), one row a floor (FLOOR)."""
    mesh = trimesh.load(model, force="mesh")
    upright = np.abs(mesh.face_normals[:, 1]) < UPRIGHT
    faces = mesh.submesh([np.nonzero(upright)[0]], append=True)
    count = int(faces.area / (FLOOR * BAY))
    if count == 0:
        return None
    centres, face_index = trimesh.sample.sample_surface_even(faces, count, seed=seed)
    lit = np.random.default_rng(seed).random(len(centres)) < LIT
    centres, normals = centres[lit], faces.face_normals[face_index[lit]]
    normals[:, 1] = 0.0
    normals /= np.linalg.norm(normals, axis=1, keepdims=True)
    low = mesh.bounds[0][1]
    centres[:, 1] = low + (np.floor((centres[:, 1] - low) / FLOOR) + 0.5) * FLOOR
    up = np.array([0.0, 1.0, 0.0])
    across = np.cross(up, normals)
    middles = centres + normals * PROUD
    corners = [middles + across * side * WINDOW[0] / 2 + up * rise * WINDOW[1] / 2
               for side, rise in ((-1, -1), (1, -1), (1, 1), (-1, 1))]
    points = np.stack(corners, axis=1).reshape(-1, 3)
    first = np.arange(len(middles))[:, None] * 4
    triangles = np.concatenate([first + [0, 1, 2], first + [0, 2, 3]])
    uvs = np.tile([[0.0, 0.0], [1.0, 0.0], [1.0, 1.0], [0.0, 1.0]], (len(middles), 1))
    return {"points": points, "triangles": triangles, "uvs": uvs, "surface": WINDOW_SURFACE}


def tower_turn(facing):
    """A tower's turn about up so its front (+z, the kit frame's) looks along the plan's bearing `facing`."""
    angle = math.radians(180.0 - facing)
    return Gf.Quath(math.cos(angle / 2.0), Gf.Vec3h(0.0, math.sin(angle / 2.0), 0.0))


def write_towers(stage, city, models, out):
    """The towers as one point instancer, a prototype per kind; {kind: count}."""
    instancer = UsdGeom.PointInstancer.Define(stage, f"/{PLACE}/Towers")
    kinds = sorted({tower["kind"] for tower in city["towers"]})
    boxes = {}
    for number, kind in enumerate(kinds):
        model = model_file(models, kind)
        if model is None:
            raise SystemExit(f"{kind}: the plan lays it but {models} has no made model of it")
        prototype = UsdGeom.Xform.Define(stage, f"/{PLACE}/Towers/Prototypes/{kind}")
        # the launch inventory's row this kind is, so a place showing the city shows its rows (complete.py's rows)
        prototype.GetPrim().CreateAttribute("score:row", Sdf.ValueTypeNames.String).Set(kind)
        body = UsdGeom.Xform.Define(stage, f"/{PLACE}/Towers/Prototypes/{kind}/body")
        boxes[kind] = glb_asset.asset(model, out / "assets" / f"{kind}.usdc", out / "assets/textures")
        body.GetPrim().GetReferences().AddReference(f"../assets/{kind}.usdc")
        windows = window_lights(model, number + int(city["seed"]))
        if windows is not None:
            prim = scene.mesh_prim(stage, f"/{PLACE}/Towers/Prototypes/{kind}/windows", windows)
            scene.bind_surface(stage, prim, PLACE, windows["surface"])
        instancer.GetPrototypesRel().AddTarget(prototype.GetPath())
    indices, positions, turns, scales = [], [], [], []
    for tower in city["towers"]:
        low, high = (np.asarray(corner, dtype=float) for corner in boxes[tower["kind"]])
        scale = float(tower["height"]) / float(high[1] - low[1])
        x, z = tower["at"]
        indices.append(kinds.index(tower["kind"]))
        positions.append(Gf.Vec3f(float(x), float(LAND_HIGH - low[1] * scale), float(z)))
        turns.append(tower_turn(float(tower["facing"])))
        scales.append(Gf.Vec3f(scale, scale, scale))
    instancer.CreateProtoIndicesAttr(Vt.IntArray(indices))
    instancer.CreatePositionsAttr(Vt.Vec3fArray(positions))
    instancer.CreateOrientationsAttr(Vt.QuathArray(turns))
    instancer.CreateScalesAttr(Vt.Vec3fArray(scales))
    return {kind: indices.count(number) for number, kind in enumerate(kinds)}


def write_ground(stage, city):
    """The land, the mountains and the harbour, each a mesh painted with its library surface."""
    for name, built, kind in (("Land", land_mesh(city), "ground"), ("Mountains", mountain_mesh(city), "ground"),
                              ("Harbour", harbour_mesh(city), "water")):
        prim = scene.mesh_prim(stage, f"/{PLACE}/{name}", built)
        scene.bind_surface(stage, prim, PLACE, built["surface"])
        for key, value in (("score:kind", kind), ("score:plain", kind),
                           ("score:from", "tools/usd/far_city.py's plan of the far shore and its mountains")):
            prim.GetPrim().CreateAttribute(key, Sdf.ValueTypeNames.String).Set(value)


def write_stage(city, models, out):
    """The far city's stage at <out>/far_city/far_city.usda, laid out as every place's (export.py): the city in its
    base layer, the creator's edit layer kept, the root over both, and the inputs record beside it; its path and the
    towers laid of each kind."""
    folder = pathlib.Path(out) / PLACE
    counts = write_base(city, models, folder)
    export.ensure_edit(folder)
    path = export.write_root(PLACE, folder)
    complete.record_inputs(folder, far_city.INVENTORY, [far_city.KINDS],
                           {kind: model_file(models, kind) for kind in counts})
    return path, counts


def write_base(city, models, folder):
    """The city written whole into the stage's base layer (<folder>/layers/base.usda); the towers laid of each kind."""
    path = folder / "layers/base.usda"
    path.parent.mkdir(parents=True, exist_ok=True)
    layer = Sdf.Layer.FindOrOpen(str(path)) or Sdf.Layer.CreateNew(str(path))
    layer.Clear()
    layer.documentation = BASE_NOTE
    stage = Usd.Stage.Open(layer)
    root = UsdGeom.Xform.Define(stage, f"/{PLACE}")
    Usd.ModelAPI(root).SetKind(Kind.Tokens.assembly)
    UsdGeom.Scope.Define(stage, f"/{PLACE}/Library")
    export.library_materials(stage, STYLE, f"/{PLACE}")
    counts = write_towers(stage, city, models, folder)
    write_ground(stage, city)
    for key, value in (("score:kind", "place"), ("score:seed", str(city["seed"])),
                       ("score:from", "tools/usd/far_city.py plan (seeded), tools/usd/far_city_stage.py")):
        root.GetPrim().CreateAttribute(key, Sdf.ValueTypeNames.String).Set(value)
    layer.Save()
    return counts


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--seed", type=int, default=7)
    parser.add_argument("--out", required=True, type=pathlib.Path)
    parser.add_argument("--models", type=pathlib.Path, default=far_city.MODELS)
    arguments = parser.parse_args()
    made = made_kinds(arguments.models)
    if not made:
        raise SystemExit(f"{arguments.models}: no tower kind is made yet")
    left = sorted(kind["row"] for kind in far_city.kinds() if kind["row"] not in made)
    path, counts = write_stage(far_city.plan(arguments.seed, made), arguments.models, arguments.out)
    print(f"{path}: {sum(counts.values())} towers ({json.dumps(counts)}); not made, so not laid: {', '.join(left) or 'none'}")


if __name__ == "__main__":
    main()
