"""The motion stage: what moves in a place, moving in its OpenUSD stage with the game's own timing.

    .venv/bin/python tools/usd/motion.py <place> --stage <the place's stage folder (export.py --out)>

It writes `<stage>/layers/motion.usda`, a layer of its own between the creator's edit layer and the base
(export.STAGE_LAYERS), from the place's motion record (`data/motion/<place>.json`). Each motion is OpenUSD time samples
on a prim the base already has (a door leaf's `xformOp:translate`, a light's `inputs:intensity`), written as an `over`;
a thing the game moves but the base does not draw while it stands still (the airlock's inner door, sunk out of sight
with air in the chamber; a warning light that is dark until a cycle runs) is added by its motion's `adds`, and is the
one `def` the layer holds. The layer runs at the stage's own time codes a second (the root's, 24 when it names none).

A motion record:

    {"place": ..., "about": ..., "motions": [{
        "name", "prim",                      the moving prim, a path in the place's stage
        "start", "length", "loop",           its cycle in seconds of the stage's time: when it starts, how long one
                                             round is, and whether it runs round again (a one-off event plays once)
        "slide": {"by", "speed", "starts", "moves": [[seconds, "open" | "shut"], ...]}
                                             a door: from where the base stands it ("shut") `by` metres ("open"), at
                                             the game's speed in metres a second, toward each end at its moment in
                                             the round, as the game's move_toward moves it
      | "light": {"on": [[from, to], ...]}  a light: at its full intensity between each pair, dark the rest
      | "climb": {"lift", "push", "pull"}   a rocket: standing until `lift`, then rising straight up at its engine's
                                             push less the world's pull (metres a second a second)
        "adds": {"like": <prim>, "at", "yaw"} | {"light": <a scene record light>}
                                             a thing the base lacks: a copy of another prim stood elsewhere, or a
                                             light written as the scene record writes its lights (tools/usd/scene.py)
        "sounds": [{"name", "at", "loops_until", "from"}]
                                             the sounds the game plays with it, in the motion's own seconds (the sound
                                             stage, tools/usd/sound.py, plays them from the prim; none written here)
        "from"                               where in the game its numbers were read
    }]}

A looping motion's samples are written round after round up to `seconds` (WRITTEN_SECONDS by default); a round must
end where it starts, so the rounds join. A sample is written only where the motion changes: a slide's ends of travel,
a light's switching (two samples a hair apart, so it switches rather than fades), a climb every time code. Where the
creator's edit layer sets a moving prim's own value, the edit wins and the prim stands still: the edit is stronger.
"""
import argparse
import json
import pathlib
import sys

import numpy as np
from pxr import Gf, Sdf, Usd, UsdGeom, UsdLux

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(HERE))
import export  # noqa: E402
import scene as scene_record  # noqa: E402

MOTIONS = REPO / "data/motion"
LAYER = "layers/motion.usda"
NOTE = "Generated by tools/usd/motion.py from the place's motion record (data/motion); rewritten on every run."
# How many seconds of the stage's time a looping motion is written for: the demo's walk-through (4 shots of 3.5 s)
# and the review's walk fit well inside.
WRITTEN_SECONDS = 60.0
# How far apart, in time codes, the two samples of a light's switch stand.
SWITCH = 1e-3
OPEN, SHUT = "open", "shut"


def code(seconds, rate):
    """A moment in seconds as the stage's time code, rounded clear of the float's last digits."""
    return round(seconds * rate, 6)


def record(place):
    """The place's motion record, or None for a place where nothing moves."""
    path = MOTIONS / f"{place}.json"
    return json.loads(path.read_text()) if path.exists() else None


# --- when ---------------------------------------------------------------------------------------------------------

def slide_keys(slide):
    """One round of a slide as (seconds, share open) keys, share 0 shut and 1 open, from its first moment to its last
    arrival: moved at the game's speed toward each end in turn (move_toward), never two moves at once."""
    reach = float(np.linalg.norm(slide["by"]))
    travel = reach / float(slide["speed"])
    share = 1.0 if slide["starts"] == OPEN else 0.0
    keys, free_at = [(0.0, share)], 0.0
    for seconds, toward in slide["moves"]:
        seconds, wanted = float(seconds), 1.0 if toward == OPEN else 0.0
        if seconds < free_at:
            raise ValueError(f"a move at {seconds} s starts before the one before it ends ({free_at:.3f} s)")
        keys.append((seconds, share))
        free_at = seconds + abs(wanted - share) * travel
        share = wanted
        keys.append((free_at, share))
    return keys


def light_switches(motion, seconds):
    """A light's switches as (seconds, on) from the stage's start: dark, then on and off at each span's ends, round
    after round for a loop; spans that meet (one round's last and the next's first) are one span."""
    start, length = float(motion.get("start", 0.0)), float(motion["length"])
    spans, offset = [], start
    while True:
        for begin, end in motion["light"]["on"]:
            if float(end) > length + 1e-9:
                raise ValueError(f"{motion['name']}: a span runs past its length of {length} s")
            begin, end = offset + float(begin), offset + float(end)
            if spans and abs(spans[-1][1] - begin) < 1e-9:
                spans[-1] = (spans[-1][0], end)
            else:
                spans.append((begin, end))
        offset += length
        if not motion.get("loop") or offset >= seconds:
            break
    switches = [(0.0, 0.0)]
    for begin, end in spans:
        if begin <= 0.0:
            switches[0] = (0.0, 1.0)
        else:
            switches.append((begin, 1.0))
        switches.append((end, 0.0))
    return switches


def rounds(keys, motion, seconds):
    """A round's keys laid at the motion's start and, for a loop, again every `length` up to `seconds`."""
    start, length = float(motion.get("start", 0.0)), float(motion["length"])
    if keys[-1][0] > length + 1e-9:
        raise ValueError(f"{motion['name']}: its round runs to {keys[-1][0]:.3f} s, past its length of {length} s")
    if motion.get("loop") and abs(keys[0][1] - keys[-1][1]) > 1e-9:
        raise ValueError(f"{motion['name']}: a looping round must end where it starts")
    laid, offset = [], start
    while True:
        laid += [(offset + moment, value) for moment, value in keys]
        offset += length
        if not motion.get("loop") or offset >= seconds:
            return laid


def climb_height(climb, seconds):
    """How far a climbing rocket has risen `seconds` into its motion: none before lift, then half its net push times
    the time since lift squared."""
    since = max(0.0, seconds - float(climb["lift"]))
    return 0.5 * (float(climb["push"]) - float(climb["pull"])) * since * since


# --- where --------------------------------------------------------------------------------------------------------

def rest_translate(stage, path):
    """Where the base (and any edit) stands a prim, as its translate op's value; zero for a built mesh with none."""
    prim = stage.GetPrimAtPath(path)
    if not prim:
        raise ValueError(f"the stage has no prim {path}")
    for operation in UsdGeom.Xformable(prim).GetOrderedXformOps():
        if operation.GetOpName() == "xformOp:translate":
            return np.asarray(operation.Get(), dtype=np.float64), True
    return np.zeros(3), False


def translate_attribute(stage, path, has_op):
    """The prim's translate attribute in the motion layer; one given its own op where the base has none."""
    prim = stage.OverridePrim(path)
    attribute = prim.CreateAttribute("xformOp:translate", Sdf.ValueTypeNames.Double3)
    if not has_op:
        prim.CreateAttribute("xformOpOrder", Sdf.ValueTypeNames.TokenArray).Set(["xformOp:translate"])
    return attribute


def added(stage, motion):
    """A thing the base lacks, defined in the motion layer: a copy of another prim (an internal reference) stood at
    `at` and turned `yaw` degrees, or a light as the scene record writes it, dark until its motion lights it."""
    adds, path = motion["adds"], motion["prim"]
    if "light" in adds:
        scene_record.write_light(stage, path, adds["light"])
        return
    if not stage.GetPrimAtPath(adds["like"]):
        raise ValueError(f"{motion['name']}: the stage has no prim {adds['like']} to copy")
    prim = stage.DefinePrim(path, "Xform")
    prim.GetReferences().AddInternalReference(adds["like"])
    prim.CreateAttribute("xformOp:translate", Sdf.ValueTypeNames.Double3).Set(Gf.Vec3d(*map(float, adds["at"])))
    prim.CreateAttribute("xformOp:rotateY", Sdf.ValueTypeNames.Float).Set(float(adds.get("yaw", 0.0)))
    prim.CreateAttribute("score:from", Sdf.ValueTypeNames.String).Set(adds.get("from", ""))


def write_slide(stage, motion, rate, seconds):
    slide = motion["slide"]
    rest, has_op = rest_translate(stage, motion["prim"])
    by = np.asarray(slide["by"], dtype=np.float64)
    attribute = translate_attribute(stage, motion["prim"], has_op)
    for moment, share in rounds(slide_keys(slide), motion, seconds):
        attribute.Set(Gf.Vec3d(*(rest + by * share)), code(moment, rate))


def write_light(stage, motion, rate, seconds):
    prim = stage.GetPrimAtPath(motion["prim"])
    if not prim or not prim.IsA(UsdLux.SphereLight):
        raise ValueError(f"{motion['name']}: {motion['prim']} is not a light in the stage")
    full = float(UsdLux.SphereLight(prim).GetIntensityAttr().Get())
    attribute = stage.OverridePrim(motion["prim"]).CreateAttribute("inputs:intensity", Sdf.ValueTypeNames.Float)
    switches = light_switches(motion, seconds)
    attribute.Set(full * switches[0][1], 0.0)
    for moment, on in switches[1:]:  # held until a hair before the switch, so it switches rather than fades
        attribute.Set(full * (1.0 - on), code(moment, rate) - SWITCH)
        attribute.Set(full * on, code(moment, rate))


def write_climb(stage, motion, rate, seconds):
    rest, has_op = rest_translate(stage, motion["prim"])
    attribute = translate_attribute(stage, motion["prim"], has_op)
    start = float(motion.get("start", 0.0))
    attribute.Set(Gf.Vec3d(*rest), code(start, rate))
    for tick in range(int(np.ceil((start + float(motion["climb"]["lift"])) * rate)), int(seconds * rate) + 1):
        height = climb_height(motion["climb"], tick / rate - start)
        attribute.Set(Gf.Vec3d(*(rest + np.array([0.0, height, 0.0]))), float(tick))


WRITERS = {"slide": write_slide, "light": write_light, "climb": write_climb}


def kind_of(motion):
    kinds = [kind for kind in WRITERS if kind in motion]
    if len(kinds) != 1:
        raise ValueError(f"{motion['name']}: a motion is one of {', '.join(WRITERS)}, not {kinds or 'none'}")
    return kinds[0]


# --- the layer ----------------------------------------------------------------------------------------------------

def working_stage(place, out, layer):
    """The place's stage with the motion layer strongest of its root's layers and every write going into it, so what
    the layer adds (a light, a copied door) is read back composed with the base it stands on."""
    root = Sdf.Layer.FindOrOpen(str(pathlib.Path(out) / f"{place}.usda"))
    if root is None:
        raise ValueError(f"no stage at {out}/{place}.usda: export it first (tools/usd/export.py)")
    others = [str(pathlib.Path(out) / path) for path in root.subLayerPaths if path != f"./{LAYER}"]
    stand_in = Sdf.Layer.CreateAnonymous(".usda")
    stand_in.subLayerPaths[:] = [layer.identifier, *others]
    stage = Usd.Stage.Open(stand_in)
    stage.SetEditTarget(Usd.EditTarget(layer))
    return stage


def stage_rate(place, out):
    """The stage's time codes a second: its root's, 24 when it names none (as OpenUSD reads it)."""
    root = Sdf.Layer.FindOrOpen(str(pathlib.Path(out) / f"{place}.usda"))
    return root.timeCodesPerSecond if root.HasTimeCodesPerSecond() else 24.0


def write_layer(place, motions, out, seconds=WRITTEN_SECONDS):
    """The motion layer of the place's stage under `out`, rewritten whole; what it moved, by name."""
    out = pathlib.Path(out)
    rate = stage_rate(place, out)
    path = out / LAYER
    path.parent.mkdir(parents=True, exist_ok=True)
    layer = Sdf.Layer.FindOrOpen(str(path)) or Sdf.Layer.CreateNew(str(path))
    layer.Clear()
    layer.documentation = NOTE
    layer.timeCodesPerSecond = rate
    layer.framesPerSecond = rate
    layer.startTimeCode = 0.0
    layer.endTimeCode = seconds * rate
    stage = working_stage(place, out, layer)
    moved = []
    for motion in motions["motions"]:
        if "adds" in motion:
            added(stage, motion)
        WRITERS[kind_of(motion)](stage, motion, rate, seconds)
        stage.GetPrimAtPath(motion["prim"]).CreateAttribute(
            "score:motion:from", Sdf.ValueTypeNames.String).Set(motion.get("from", ""))
        moved.append(motion["name"])
    for prim in layer.rootPrims:  # the place and its scopes are the base's
        overs(prim)
    layer.Save()
    export.held_by_root(place, out)
    return {"moved": moved, "layer": str(path)}


def overs(spec):
    """Every typeless def the layer made on the way down to what it adds is turned into an over of the base's prim."""
    if spec.specifier == Sdf.SpecifierDef and not spec.typeName:
        spec.specifier = Sdf.SpecifierOver
    for child in spec.nameChildren:
        overs(child)


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("place")
    parser.add_argument("--stage", required=True, type=pathlib.Path, help="the place's stage folder (export.py --out)")
    parser.add_argument("--record", type=pathlib.Path, help="the motion record, by default data/motion/<place>.json")
    arguments = parser.parse_args()
    motions = json.loads(arguments.record.read_text()) if arguments.record else record(arguments.place)
    if motions is None:
        raise SystemExit(f"{arguments.place} has no motion record (data/motion/{arguments.place}.json)")
    print(json.dumps(write_layer(arguments.place, motions, arguments.stage)))


if __name__ == "__main__":
    main()
